version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: laravel_prod
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nextjs_prod
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app_network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend
    networks:
      - app_network
    ports:
      - "80:80"

volumes:
  db_data:

networks:
  app_network:
