version: '3.8'

services:
  app:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: laravel_dev
    working_dir: /var/www/html
    volumes:
      - ./api-service:/var/www/html
    network_mode: host
    depends_on:
      - db
    env_file:
      - api-service/.env
    command: php artisan serve

  db:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    network_mode: host

volumes:
  dbdata:
