version: '3.8'

services:
  app:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: laravel_dev
    working_dir: /var/www/html
    volumes:
      - ./api-service:/var/www/html
    network_mode: host
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    network_mode: host

volumes:
  dbdata:
